export enum Status {
  EMPTY = 'EMPTY',
  PLAYER_COUNT = 'PLAYER_COUNT',
  PLAYER_INFO = 'PLAYER_INFO',
  DEALING = 'DEALING',
  PREDICTION = 'PREDICTION',
  PLAYING = 'PLAYING',
  OVERVIEW = 'OVERVIEW',
  GAME_END = 'GAME_END',
  ROUND_END = 'ROUND_END',
}
